import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../src/compoents/ui/Header'

const Home: NextPage = () => {
  return (
    <div style={{ padding: "16px 56px" }}>
      <Head>
        <title>vintoker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
    </div>
  )
}

export default Home
